## Basic Configuration

baseurl = "https://andr3a88.github.io"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Andrea Stevanato"
title = "Andrea Stevanato - Senior iOS Developer - andr3a88"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "andr3a88" # Comment out to disable Disqus.
#googleAnalytics = "UA-15186983-3"
enableRobotsTXT = true

## Site Settings
[params]
author = "Andrea Stevanato"
intro = "Tech Lead and iOS Developer. Swift and clean code enthusiast. Also working on backend development with NodeJS, Typescript."
description = "Now @ Amiko.io"
authorimage = "andrea.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Andrea Stevanato Personal web site"
keywords = "blog,developer,swift,swiftlang,ios,developer,ios-dev,ios developer,ios-dev,ios developer,ios,developer,ios-dev,ios developer,swift,swiftlang,blog,developer,swift,swiftlang,ios,developer,ios-dev,ios developer,ios-dev,ios developer,ios,developer,ios-dev,ios developer,swift,swiftlang, ai, artificial intelligence, machine learning, deep learning, data science, big data, neural networks, natural language processing, computer vision, robotics, automation"

## Social Accounts
[params.social]
github = "andr3a88"
linkedin = "andrea-stevanato-27826187"
twitter = "andrea_steva"
stackoverflow = "andr3a88"
medium = "@andr3a88"

## Extras
[params.extra]
copyright = "© 2026. Andrea Stevanato. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = false
hightlightjs = true
rss = false 
socialmarkup = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 200
    identifier = "blog"
    url = "/blog/"